"""initial schema

Revision ID: 93f15307ea9f
Revises: 
Create Date: 2026-09-09 09:18:10.671010
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '93f15307ea9f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_full_name', sa.String(length=512), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=True),
    sa.Column('event_action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('added_lines', sa.Integer(), nullable=False),
    sa.Column('deleted_lines', sa.Integer(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('partial_reason', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('raw_diff', sa.Text(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'pr_number', 'head_sha', name='uq_review_repo_pr_sha')
    )
    op.create_index(op.f('ix_reviews_repository_id'), 'reviews', ['repository_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('diff_position', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.Column('drop_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_dropped'), 'findings', ['dropped'], unique=False)
    op.create_index(op.f('ix_findings_review_id'), 'findings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_review_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_dropped'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_repository_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
