"""Per-file classification.

Two orthogonal axes, deliberately separate — conflating them is why "is this a test
file" becomes hard to answer later:

    language   how to parse it       python, yaml, dockerfile, binary, …
    category   what role it plays    source, test, dependency, documentation, config,
                                     generated

Everything here is table data rather than `if` chains, so adding a language is a
one-line change and the rules can be read without tracing control flow.

`reviewed` is computed separately from both axes: a file can be perfectly well
classified as `python`/`source` and still not be reviewed because it is deleted, or
oversized, or matched an ignore glob. Keeping that a third output rather than folding
it into `category` is what makes "which files did we actually look at, and why not the
others" answerable after the fact.
"""

from __future__ import annotations

import posixpath
from dataclasses import dataclass
from typing import Literal

import pathspec

Language = Literal[
    "python",
    "javascript",
    "typescript",
    "go",
    "ruby",
    "java",
    "kotlin",
    "rust",
    "php",
    "csharp",
    "swift",
    "scala",
    "shell",
    "sql",
    "yaml",
    "json",
    "toml",
    "markdown",
    "text",
    "dockerfile",
    "dependency",
    "binary",
    "unknown",
]

Category = Literal[
    "source",
    "test",
    "dependency",
    "documentation",
    "config",
    "generated",
]

# --- tables -------------------------------------------------------------------------

EXTENSION_LANGUAGE: dict[str, Language] = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".go": "go",
    ".rb": "ruby",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".rs": "rust",
    ".php": "php",
    ".cs": "csharp",
    ".swift": "swift",
    ".scala": "scala",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".sql": "sql",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".json": "json",
    ".toml": "toml",
    ".ini": "toml",
    ".cfg": "toml",
    ".md": "markdown",
    ".mdx": "markdown",
    ".rst": "markdown",
    ".txt": "text",
}

# Matched against the basename, case-insensitively, before extensions are considered.
FILENAME_LANGUAGE: dict[str, Language] = {
    "dockerfile": "dockerfile",
    "containerfile": "dockerfile",
    "makefile": "shell",
    "go.mod": "dependency",
    "go.sum": "dependency",
}

# Content that is unmistakably not source code, regardless of extension.
BINARY_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".svg",
        ".pdf", ".zip", ".gz", ".tar", ".bz2", ".xz", ".7z",
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        ".mp3", ".mp4", ".wav", ".mov", ".avi",
        ".so", ".dylib", ".dll", ".exe", ".bin", ".class", ".pyc", ".o", ".a",
        ".db", ".sqlite", ".sqlite3", ".parquet",
    }
)

# Default role for a language, when no earlier rule has claimed the file.
LANGUAGE_CATEGORY: dict[Language, Category] = {
    "markdown": "documentation",
    "text": "documentation",
    "yaml": "config",
    "json": "config",
    "toml": "config",
    "dockerfile": "config",
    "dependency": "dependency",
    "binary": "generated",
}

# gitignore-style. `*.lock` matches at any depth; `migrations/` matches a directory
# anywhere, which is the behaviour fnmatch silently failed to provide.
GENERATED_PATH_PATTERNS: tuple[str, ...] = (
    "*.lock",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*.pb.go",
    "*.generated.*",
    "dist/",
    "build/",
    "migrations/",
    "vendor/",
    "node_modules/",
    "__snapshots__/",
)

# Sniffed in the first few lines of file content. Cheap, and catches generated files
# that no path pattern would.
GENERATED_CONTENT_MARKERS: tuple[str, ...] = (
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "autogenerated",
    "Auto-generated",
)
_CONTENT_SNIFF_BYTES = 2000

TEST_PATTERNS: tuple[str, ...] = (
    "test/",
    "tests/",
    "spec/",
    "testing/",
    "test_*.py",
    "*_test.py",
    "*_test.go",
    "*_test.rb",
    "*Test.java",
    "*Tests.cs",
    "*.test.js",
    "*.test.ts",
    "*.test.tsx",
    "*.spec.js",
    "*.spec.ts",
    "*.spec.tsx",
    "conftest.py",
)

DEPENDENCY_MANIFESTS: frozenset[str] = frozenset(
    {
        "package.json",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "requirements.txt",
        "requirements-dev.txt",
        "pyproject.toml",
        "poetry.lock",
        "pipfile",
        "pipfile.lock",
        "go.mod",
        "go.sum",
        "gemfile",
        "gemfile.lock",
        "cargo.toml",
        "cargo.lock",
        "composer.json",
        "composer.lock",
        "build.gradle",
        "pom.xml",
    }
)
_DEPENDENCY_PREFIXES: tuple[str, ...] = ("requirements",)

# Which roles are worth spending a review on. Changing this line changes what gets
# reviewed — it is the whole policy, in one place.
#
# `config` is excluded for now to preserve existing behaviour. Including it is the
# obvious next widening: a Dockerfile or a CI workflow is exactly where a
# privilege-escalation or secret-exposure bug hides, and PRGuard is blind to both today.
REVIEWABLE_CATEGORIES: frozenset[Category] = frozenset({"source", "test", "dependency"})


@dataclass(frozen=True, slots=True)
class FileClassification:
    language: Language
    category: Category
    reviewed: bool
    skip_reason: str | None = None


def _spec(patterns: tuple[str, ...] | list[str]) -> pathspec.PathSpec[pathspec.Pattern]:
    return pathspec.PathSpec.from_lines("gitwildmatch", patterns)


_GENERATED_SPEC = _spec(GENERATED_PATH_PATTERNS)
_TEST_SPEC = _spec(TEST_PATTERNS)


def matches_globs(path: str, globs: list[str]) -> bool:
    """gitignore-style path matching.

    Replaces fnmatch, which treats `**/migrations/**` as requiring a leading directory
    and therefore missed a top-level `migrations/`.
    """
    if not globs:
        return False
    return _spec(globs).match_file(path)


def looks_generated(content: str) -> bool:
    head = content[:_CONTENT_SNIFF_BYTES]
    return any(marker in head for marker in GENERATED_CONTENT_MARKERS)


def language_for(path: str) -> Language:
    name = posixpath.basename(path).lower()
    if name in FILENAME_LANGUAGE:
        return FILENAME_LANGUAGE[name]
    # `Dockerfile.prod`, `dockerfile.dev`
    if name.startswith("dockerfile"):
        return "dockerfile"
    # Manifests win over their own extension: package.json is a dependency file, not
    # "some JSON". Matches the worked example in phase-03-pr-analyzer.md.
    if name in DEPENDENCY_MANIFESTS or name.startswith(_DEPENDENCY_PREFIXES):
        return "dependency"
    _, _, ext = name.rpartition(".")
    suffix = f".{ext}" if ext and ext != name else ""
    if suffix in BINARY_EXTENSIONS:
        return "binary"
    return EXTENSION_LANGUAGE.get(suffix, "unknown")


def _category_for(path: str, language: Language, content: str | None) -> Category:
    """First match wins, in the order the spec lays out."""
    name = posixpath.basename(path).lower()

    if _GENERATED_SPEC.match_file(path):
        return "generated"
    if content is not None and looks_generated(content):
        return "generated"
    if _TEST_SPEC.match_file(path):
        return "test"
    if name in DEPENDENCY_MANIFESTS or name.startswith(_DEPENDENCY_PREFIXES):
        return "dependency"
    return LANGUAGE_CATEGORY.get(language, "source")


def classify(
    path: str,
    *,
    content: str | None = None,
    has_patch: bool = True,
    change_type: str = "modified",
    ignore_globs: list[str] | None = None,
) -> FileClassification:
    """Classify one changed file.

    `content` is optional — classification works from the path alone, and the content
    sniff only sharpens generated-file detection. That matters because classification
    runs before we decide which files are worth fetching.
    """
    language = language_for(path)
    category = _category_for(path, language, content)

    # Disqualifiers, most specific first. The first one that fires is the reason
    # recorded, so "why wasn't this reviewed" has a single unambiguous answer.
    reason: str | None = None
    if change_type == "removed":
        reason = "deleted"
    elif ignore_globs and matches_globs(path, ignore_globs):
        reason = "ignored_path"
    elif language == "binary":
        # Checked before `generated` because it is the more informative answer: a .png
        # is categorised `generated` only as a fallback.
        reason = "binary"
    elif category == "generated":
        reason = "generated"
    elif not has_patch:
        # Binary, oversized, or a mode-only change — GitHub omits the patch for all
        # three and does not say which.
        reason = "no_patch"
    elif category not in REVIEWABLE_CATEGORIES:
        reason = f"category_{category}"

    return FileClassification(
        language=language,
        category=category,
        reviewed=reason is None,
        skip_reason=reason,
    )
