"""Context assembly.

Builds the two blocks the reviewer sees: repository content (cacheable) and the diff
(not cacheable). Everything here is repository content authored by whoever opened the
PR, so it is rendered as clearly-delimited, line-numbered *data* — never as prose that
could read as instruction.
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass

from github.diff import FileDiff

# Extensions worth sending as full file content. Everything else is reviewed from its
# diff alone.
SOURCE_EXTENSIONS = frozenset(
    {
        ".py",
        ".pyi",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".go",
        ".rb",
        ".java",
        ".kt",
        ".rs",
        ".php",
        ".cs",
        ".swift",
        ".scala",
        ".sh",
        ".sql",
    }
)

GENERATED_MARKERS = ("@generated", "Code generated by", "DO NOT EDIT", "autogenerated")

# Framing that repository content must not be able to forge.
DELIMITER_PATTERNS = (
    "</repository_content>",
    "<repository_content",
    "</file>",
    "<system>",
    "<system-reminder>",
    "\nHuman:",
    "\nAssistant:",
)


@dataclass(slots=True)
class ContextBundle:
    repository_block: str
    diff_block: str
    included_paths: list[str]
    skipped_paths: list[str]
    truncated: bool = False


def is_ignored(path: str, globs: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, g) for g in globs)


def looks_generated(content: str) -> bool:
    head = content[:2000]
    return any(marker in head for marker in GENERATED_MARKERS)


def is_source(path: str) -> bool:
    return any(path.endswith(ext) for ext in SOURCE_EXTENSIONS)


def neutralise(text: str) -> str:
    """Strip framing that repository content could use to escape its delimiters.

    Injection is not *solved* by this — it is one layer. The structural guarantee is
    that the model can only return a FindingsReport, so injected instructions cannot
    become arbitrary output. This just stops the cheapest trick.
    """
    cleaned = text
    for pattern in DELIMITER_PATTERNS:
        if pattern in cleaned:
            # Escape the characters that give the pattern its structural meaning:
            # angle brackets for tags, and the colon for conversation-turn markers
            # like "Human:". Escaping only brackets would leave "Human:" intact.
            escaped = pattern.replace("<", "&lt;").replace(">", "&gt;").replace(":", "&#58;")
            cleaned = cleaned.replace(pattern, escaped)
    return cleaned


def render_numbered(content: str, *, start: int = 1) -> str:
    """Line-number a file so the model can cite a line and we can verify the citation."""
    lines = content.split("\n")
    width = len(str(start + len(lines) - 1))
    return "\n".join(f"{i:>{width}} | {line}" for i, line in enumerate(lines, start=start))


def build_context(
    *,
    title: str,
    description: str,
    files: list[FileDiff],
    file_contents: dict[str, str],
    max_chars: int,
) -> ContextBundle:
    """Assemble the repository and diff blocks.

    Rendering is deterministic — files in a stable order, no timestamps, no IDs — so
    the repository block is byte-identical across reviews of the same commit and can
    sit behind a prompt-cache breakpoint.
    """
    included: list[str] = []
    skipped: list[str] = []
    truncated = False

    parts: list[str] = ['<repository_content untrusted="true">']
    budget = max_chars

    for diff in sorted(files, key=lambda f: f.path):
        content = file_contents.get(diff.path)
        if content is None:
            skipped.append(diff.path)
            continue
        if looks_generated(content):
            skipped.append(diff.path)
            continue

        rendered = f'<file path="{neutralise(diff.path)}">\n{render_numbered(neutralise(content))}\n</file>'
        if len(rendered) > budget:
            truncated = True
            skipped.append(diff.path)
            continue

        parts.append(rendered)
        budget -= len(rendered)
        included.append(diff.path)

    parts.append("</repository_content>")

    diff_parts: list[str] = [
        "<pull_request>",
        f"<title>{neutralise(title)}</title>",
        f"<description>\n{neutralise(description[:4000])}\n</description>",
        "<diff>",
    ]
    for diff in sorted(files, key=lambda f: f.path):
        if not diff.patch:
            continue
        diff_parts.append(f'<file_diff path="{neutralise(diff.path)}" change="{diff.change_type}">')
        diff_parts.append(neutralise(diff.patch))
        diff_parts.append("</file_diff>")
    diff_parts.extend(["</diff>", "</pull_request>"])

    return ContextBundle(
        repository_block="\n".join(parts),
        diff_block="\n".join(diff_parts),
        included_paths=included,
        skipped_paths=skipped,
        truncated=truncated,
    )
